# Generated by Django 4.2.1 on 2023-07-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profilepicture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/trolololol.png', null=True, upload_to='profile_images/'),
        ),
    ]
