# Generated by Django 4.2.1 on 2023-07-01 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="home.cart"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="home.product"
            ),
        ),
    ]
