# Generated by Django 4.2.1 on 2023-07-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_cartitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('home', 'Home'), ('beauty', 'Beauty'), ('books', 'Books'), ('toys', 'Toys'), ('sports', 'Sports'), ('jewelry', 'Jewelry'), ('automotive', 'Automotive'), ('health', 'Health'), ('food', 'Food'), ('music', 'Music'), ('movies', 'Movies')], max_length=50, null=True),
        ),
    ]
