# Generated by Django 4.2.1 on 2023-06-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_accounts_email_useremailconfirmationnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="username",
            field=models.CharField(max_length=15),
        ),
    ]
